// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "nick_name", Type: field.TypeString, Size: 64},
		{Name: "real_name", Type: field.TypeString, Unique: true, Size: 64},
		{Name: "email", Type: field.TypeString, Size: 64},
		{Name: "tel", Type: field.TypeString, Unique: true, Size: 12},
		{Name: "password", Type: field.TypeString, Size: 20},
		{Name: "last_login_time", Type: field.TypeInt64, Default: 0},
		{Name: "last_ip_addr", Type: field.TypeString, Default: ""},
		{Name: "create_time", Type: field.TypeInt64},
		{Name: "update_time", Type: field.TypeInt64},
		{Name: "is_deleted", Type: field.TypeInt64, Default: 0},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		UsersTable,
	}
)

func init() {
}
