// Code generated by goctl. DO NOT EDIT.
package types

type Fan struct {
	ID       int    `json:"id"`
	UserID   int    `json:"userId"`
	NickName string `json:"nickName"`
}

type FollowReq struct {
	UserID          int `form:"userid"`
	FollowingUserID int `form:"followingUserId"`
}

type FollowResp struct {
	CommonResp
	Data bool `json:"data"`
}

type GetFollowerListReq struct {
	UserID int `form:"userid"`
	Page   int `form:"page"`
	Size   int `form:"size"`
}

type GetFollowerListResp struct {
	CommonResp
	Data []Fan `json:"data"`
}

type GetFollowingListReq struct {
	UserID int `form:"userid"`
	Page   int `form:"page"`
	Size   int `form:"size"`
}

type GetFollowingListResp struct {
	CommonResp
	Data []Fan `json:"data"`
}

type GetUserInfoReq struct {
	UserID int `form:"userid"`
}

type GetUserInfoResp struct {
	CommonResp
	NickName      string `json:"nickName"`
	RealName      string `json:"realName"`
	Email         string `json:"email"`
	Tel           string `json:"tel"`
	LastLoginTime int    `json:"lastLoginTime"`
	LastIPAddr    string `json:"lastIPAddr"`
}

type LoginReq struct {
	Tel      string `form:"tel"`
	Password string `form:"password"`
}

type LoginResp struct {
	CommonResp
	NickName      string `json:"nickName"`
	RealName      string `json:"realName"`
	Tel           string `json:"tel"`
	Email         string `json:"email"`
	LastLoginTime int    `json:"lastLoginTime"`
	LastIPAddr    string `json:"lastIPAddr"`
}

type RegisterReq struct {
	NickName string `form:"nickName"`
	RealName string `form:"realName"`
	Password string `form:"password"`
	Tel      string `form:"tel"`
	Email    string `form:"email"`
}

type RegisterResp struct {
	CommonResp
	NickName      string `json:"nickName"`
	RealName      string `json:"realName"`
	Tel           string `json:"tel"`
	Email         string `json:"email"`
	LastLoginTime int64  `json:"lastLoginTime"`
	LastIPAddr    string `json:"lastIPAddr"`
}

type CommonResp struct {
	Code int32  `json:"code"`
	Msg  string `json:"msg"`
}
