// Code generated by ent, DO NOT EDIT.

package ent

import (
	"wego/apps/service/user/model/ent/user"
	"wego/apps/service/user/model/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescLastLoginTime is the schema descriptor for lastLoginTime field.
	userDescLastLoginTime := userFields[5].Descriptor()
	// user.DefaultLastLoginTime holds the default value on creation for the lastLoginTime field.
	user.DefaultLastLoginTime = userDescLastLoginTime.Default.(int64)
	// userDescLastIPAddr is the schema descriptor for lastIPAddr field.
	userDescLastIPAddr := userFields[6].Descriptor()
	// user.DefaultLastIPAddr holds the default value on creation for the lastIPAddr field.
	user.DefaultLastIPAddr = userDescLastIPAddr.Default.(string)
	// userDescIsDeleted is the schema descriptor for isDeleted field.
	userDescIsDeleted := userFields[9].Descriptor()
	// user.DefaultIsDeleted holds the default value on creation for the isDeleted field.
	user.DefaultIsDeleted = userDescIsDeleted.Default.(int64)
}
